### ISSUE TITLE
consolidate example page

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-web-services/ucsf_identity_web_banner_templates#10]
replace one million banners with just one, eliminate to need to scroll. _clean this mess up_

throw a form above the banner that lets you select color and toggle the ucsf logo on/off. 
then rig some javascript event handlers to that form to change the banner display and code snippet on form state change.

_easy_

follows #9

**Comment by johnkealy** [comment]
Agreed this is a mess... Thanks
