### ISSUE TITLE
align banner markup and css with Shoestring

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-web-services/ucsf_identity_web_banner_templates#19]
Right now, [Shoestring](https://github.com/ucsf-web-services/shoestring) shipts with its own Banner version.
_That is not good!_

Resolve any discrepancies between the two projects.

**Comment by stopfstedt** [comment]
refs ucsf-web-services/shoestring#26

**Comment by Okami-** [comment]
Going to have to change shoestring as the javascript dependency for code preview requires vanilla javascript and ID's.

**Comment by stopfstedt** [comment]
@Okami- to elaborate on this a bit -  this pair of tickets means changes on both ends, not just overriding this here with what's in shoestring. apologies if i wasn't clear enough on this.

**Comment by Okami-** [comment]
I'm going to initially make the changes for shoestring then, then port them over to this repo.

**Comment by stopfstedt** [comment]
fixed by pull request #22
