### ISSUE TITLE
cloning current repo doesn't work

### ISSUE THREAD

**Issue by Okami-** [ucsf-web-services/ucsf_identity_web_banner_templates#21]
I cloned the repo and the html preview window isn't showing and the color picker isn't working either.

**Comment by Okami-** [comment]
Current cdn prefix // isn't working. I had to add https:// to all cdn get requests.

**Comment by stopfstedt** [comment]
^ nonsense. serve this project via a web server, the protocol-relative URLs will work. PHP's built in server will do just fine.

**Comment by stopfstedt** [comment]
do this

``` bash
git clone git@github.com:ucsf-web-services/ucsf_identity_web_banner_templates.git
cd ucsf_identity_web_banner_templates
php -S localhost:4000
```

then load http://localhost:4000 in your browser.

**Comment by Okami-** [comment]
Ahhh I see. Ok I removed the https and commited the changes relational to https://github.com/ucsf-web-services/ucsf_identity_web_banner_templates/pull/22.
