### ISSUE TITLE
Poor resolution on UCSF logo

### ISSUE THREAD

**Issue by HenrikBengtsson** [ucsf-web-services/ucsf_identity_web_banner_templates#4]
Instead of rescaling the ucsf-logo-banner.png file to control the logo's dimension, I'd like to propose to use a higher resolution images and use CSS to scale it back down.  The current image has dimensions 46x22, which makes it look very pixelated, e.g.

![screenshot_ucsf-logo-banner_46x22](https://cloud.githubusercontent.com/assets/1616850/5134237/0b3a7fe6-70c1-11e4-8a75-1ef4a1d03ac3.PNG)

whereas if you use a 179x88 version of the same logo scaled to 45x22 pixels, it looks like this:

![screenshot_ucsf-logo-banner_179x88](https://cloud.githubusercontent.com/assets/1616850/5134245/1ba5c4ee-70c1-11e4-9500-13f0b40a3468.PNG)

I use:

```
    background-image: url("ucsf-logo-banner_179x88.png");
    background-size: 45px 22px; 
```

The improvement is even greater on high-resolution displays such as modern smart phones.

I attach the ucsf-logo-banner_179x88.png image below (but is "invisible" here because it's white on white):
![ucsf-logo-banner_179x88](https://cloud.githubusercontent.com/assets/1616850/5134268/5e7e08ee-70c1-11e4-8b90-0d273c14b2c1.png)
which is a scaled down version of a a much bigger version from https://github.com/UCSF-CBC/UCSF-logo/blob/master/images/ucsf_logo_K_OTL_9%2C1200dpi%2Cffffff%2Ctransparent.png.  That one in turn is generated from the official UCSF Identity logos.  See the repository for details.  Feel free to use it however you want.

**Comment by stopfstedt** [comment]
ok, as we found out `background-size` is CSS3 and incompatible with IE8 and below.
will have to build degraded support in for this, working on it...

**Comment by HenrikBengtsson** [comment]
Good point. Thanks for looking into this.

**Comment by stopfstedt** [comment]
To add more problems - image scaling is horrid in all Internet Explorers. The scaled down image looks jagged in IE9-11. :hankey: 
Looking into using [SVG](http://caniuse.com/#feat=svg-css) as an alternative to PNG background images for IE9+ and all other non-IE browsers.

**Comment by stopfstedt** [comment]
@Okami-, please see what i got so far [here](https://github.com/stopfstedt/ucsf_identity_web_banner_templates/compare/ucsf-web-services:gh-pages...gh-pages) - preview [here](http://stefan.topfstedt.me/ucsf_identity_web_banner_templates/). Thanks!

**Comment by HenrikBengtsson** [comment]
BTW, are you aware of the (now obsolete) IE CSS property `-ms-interpolation-mode` to control `bicubical` rendering, cf. http://msdn.microsoft.com/en-us/library/ie/ms530822(v=vs.85).aspx.  Example http://css-tricks.com/ie-fix-bicubic-scaling-for-images/.

**Comment by stopfstedt** [comment]
yeah, looked into it. doesn't work on background images.

**Comment by HenrikBengtsson** [comment]
Which brings me to my next question: why does it have to be a background image? If a foreground one, it would also be easy to wrap it up in a anchor so the logo - not just the text - can link to the main site, which is a feature commonly expected. ... or is there a decision that that must not be the case?

**Comment by stopfstedt** [comment]
@HenrikBengtsson good point. I have no idea whether this was a deliberate decision or not. Generally speaking, this is a content (image) vs design (background-image) issue. I would argue that the logo is part of the design. That being said - I don't see why the logo couldn't be clickable, e.g. if it was set to be the background image of the first link (which should go back to www.ucsf.edu in any case).
Like [so](http://pharm.ucsf.edu/).

**Comment by stopfstedt** [comment]
@HenrikBengtsson, please file a separate issue about the lacking ability to click on the banner logo. Thanks!

**Comment by johnkealy** [comment]
@HenrikBengtsson Thanks for finding this issue and bringing it to our attention
